"""Query helpers for package crawler artifacts."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Optional, Sequence


def find_package(
    *,
    index_data: dict,
    package_id: str,
    version: Optional[str] = None,
) -> Optional[dict]:
    """Return the matching package entry."""
    for entry in index_data.get("packages", []):
        if entry.get("packageId") != package_id:
            continue
        if version and entry.get("version") != version:
            continue
        return entry
    return None


def _parse_args(argv: Optional[Sequence[str]] = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Query external package index.")
    parser.add_argument(
        "--index",
        type=Path,
        required=True,
        help="Path to index.json generated by the collector.",
    )
    parser.add_argument(
        "--package",
        dest="package_id",
        help="Package ID to query.",
    )
    parser.add_argument(
        "--version",
        help="Optional version filter.",
    )
    return parser.parse_args(argv)


def main(argv: Optional[Sequence[str]] = None) -> int:
    args = _parse_args(argv)
    index_data = json.loads(args.index.read_text(encoding="utf-8"))
    if args.package_id:
        entry = find_package(
            index_data=index_data,
            package_id=args.package_id,
            version=args.version,
        )
        if not entry:
            print("Package not found")
        else:
            print(json.dumps(entry, indent=2))
    else:
        print(json.dumps(index_data, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
