using System;
using System.IO;
using System.Threading.Tasks;
using CSnakes.Runtime;
using GotOcr2Sample.Domain.Interfaces;
using GotOcr2Sample.Domain.Models;
using GotOcr2Sample.Domain.ValueObjects;
using GotOcr2Sample.Infrastructure;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Logging;

namespace GotOcr2Sample.ConsoleDemo;

/// <summary>
/// Console demo application for GOT-OCR2 OCR executor
/// </summary>
internal class Program
{
    private static async Task<int> Main(string[] args)
    {
        Console.WriteLine("=== GOT-OCR2 OCR Executor Demo ===\n");

        try
        {
            // Build host with Python environment
            var builder = Host.CreateApplicationBuilder(args);

            // Setup Python environment
            // Get the solution directory (parent of ConsoleDemo)
            var pythonLibPath = Path.Combine(
                AppDomain.CurrentDomain.BaseDirectory,
                "..", "..", "..", "..", "PythonOcrLib"
            );
            pythonLibPath = Path.GetFullPath(pythonLibPath);

            Console.WriteLine($"Python library path: {pythonLibPath}");

            var venvPath = Path.Combine(pythonLibPath, ".venv_clean");

            // CSnakes will download and manage its own Python redistributable
            builder.Services
                .WithPython()
                .WithHome(pythonLibPath)
                .WithVirtualEnvironment(venvPath, true)
                .FromRedistributable("3.13")
                .WithPipInstaller("requirements.txt");

            // Add logging
            builder.Logging.ClearProviders();
            builder.Logging.AddConsole();
            builder.Logging.SetMinimumLevel(LogLevel.Information);

            var host = builder.Build();

            // Install Python packages from requirements.txt (like TransformersSharp does)
            Console.WriteLine("Installing Python dependencies (this may take several minutes on first run)...");
            Console.WriteLine("✓ Python dependencies installed\n");

            // Create executor
            var pythonEnv = host.Services.GetRequiredService<IPythonEnvironment>();
            var logger = host.Services.GetRequiredService<ILogger<GotOcr2Executor>>();
            var executor = new GotOcr2Executor(pythonEnv, logger);

            // Run demos
            await RunHealthCheckDemo(pythonEnv);
            await RunOcrDemo(executor, args);

            return 0;
        }
        catch (Exception ex)
        {
            Console.ForegroundColor = ConsoleColor.Red;
            Console.WriteLine($"\n[ERROR] {ex.Message}");
            Console.ResetColor();
            Console.WriteLine($"\nStack trace:\n{ex.StackTrace}");
            return 1;
        }
    }

    private static async Task RunHealthCheckDemo(IPythonEnvironment pythonEnv)
    {
        Console.WriteLine("\n--- Health Check ---");

        try
        {
            // Use the strongly-typed interface generated by CSnakes
            var module = pythonEnv.GotOcr2Wrapper();

            // Get version and model info
            var version = module.GetVersion();
            var modelInfo = module.GetModelInfo();

            Console.WriteLine($"✓ Module version: {version}");
            Console.WriteLine($"✓ Model info: {modelInfo}");

            // Run health check
            Console.WriteLine("\nRunning health check...");
            var isHealthy = module.HealthCheck();

            if (isHealthy)
            {
                Console.ForegroundColor = ConsoleColor.Green;
                Console.WriteLine("✓ Health check PASSED");
                Console.ResetColor();
            }
            else
            {
                Console.ForegroundColor = ConsoleColor.Yellow;
                Console.WriteLine("⚠ Health check FAILED");
                Console.ResetColor();
            }
        }
        catch (Exception ex)
        {
            Console.ForegroundColor = ConsoleColor.Red;
            Console.WriteLine($"✗ Health check error: {ex.Message}");
            Console.WriteLine($"✗ Health check error: {ex.InnerException?.Message}");
            Console.ResetColor();
        }
    }

    private static async Task RunOcrDemo(IOcrExecutor executor, string[] args)
    {
        Console.WriteLine("\n--- OCR Execution Demo ---");

        // Get image path from args or use default
        string imagePath;

        if (args.Length > 0 && File.Exists(args[0]))
        {
            imagePath = args[0];
        }
        else
        {
            // Look for fixtures
            var fixturesPath = Path.Combine(
                Environment.CurrentDirectory,
                "..", "..", "..", "..", "..", "..", "Fixtures", "PRP1"
            );
            fixturesPath = Path.GetFullPath(fixturesPath);

            var jpgFiles = Directory.GetFiles(fixturesPath, "*.jpg", SearchOption.TopDirectoryOnly);

            if (jpgFiles.Length == 0)
            {
                Console.WriteLine("\n⚠ No image file specified and no fixtures found.");
                Console.WriteLine("\nUsage: ConsoleDemo <path-to-image>");
                Console.WriteLine($"  or place JPG files in: {fixturesPath}");
                return;
            }

            imagePath = jpgFiles[0];
            Console.WriteLine($"\nUsing fixture: {Path.GetFileName(imagePath)}");
        }

        Console.WriteLine($"Processing image: {imagePath}");

        // Read image
        byte[] imageBytes;
        try
        {
            imageBytes = await File.ReadAllBytesAsync(imagePath);
            Console.WriteLine($"✓ Image loaded: {imageBytes.Length:N0} bytes");
        }
        catch (Exception ex)
        {
            Console.ForegroundColor = ConsoleColor.Red;
            Console.WriteLine($"✗ Failed to read image: {ex.Message}");
            Console.ResetColor();
            return;
        }

        // Create image data
        var imageData = new ImageData(imageBytes, imagePath, 1, 1);

        // Create OCR config
        var config = new OCRConfig(
            language: "spa",
            oem: 1,
            psm: 6,
            fallbackLanguage: "eng",
            confidenceThreshold: 0.7f
        );

        Console.WriteLine($"\nOCR Configuration:");
        Console.WriteLine($"  Language: {config.Language}");
        Console.WriteLine($"  Confidence threshold: {config.ConfidenceThreshold}");

        // Execute OCR
        Console.WriteLine("\n⏳ Executing OCR (this may take a while on first run)...\n");

        var startTime = DateTime.Now;
        var result = await executor.ExecuteOcrAsync(imageData, config);
        var duration = DateTime.Now - startTime;

        Console.WriteLine($"⏱ OCR completed in {duration.TotalSeconds:F2} seconds\n");

        // Display results
        if (result.IsSuccess)
        {
            Console.ForegroundColor = ConsoleColor.Green;
            Console.WriteLine("✓ OCR succeeded");
            Console.ResetColor();

            var ocrResult = result.Value;

            Console.WriteLine("\n--- OCR Results ---");
            Console.WriteLine($"Text length: {ocrResult.Text.Length:N0} characters");
            Console.WriteLine($"Confidence avg: {ocrResult.ConfidenceAvg:F2}");
            Console.WriteLine($"Confidence median: {ocrResult.ConfidenceMedian:F2}");
            Console.WriteLine($"Confidence scores: {ocrResult.Confidences.Count}");
            Console.WriteLine($"Language used: {ocrResult.LanguageUsed}");

            Console.WriteLine("\n--- Extracted Text (first 500 chars) ---");
            var preview = ocrResult.Text.Length > 500
                ? ocrResult.Text.Substring(0, 500) + "..."
                : ocrResult.Text;

            Console.WriteLine(preview);

            // Save full text to file
            var outputFile = Path.ChangeExtension(imagePath, ".ocr.txt");
            await File.WriteAllTextAsync(outputFile, ocrResult.Text);
            Console.WriteLine($"\n✓ Full text saved to: {outputFile}");
        }
        else
        {
            Console.ForegroundColor = ConsoleColor.Red;
            Console.WriteLine($"✗ OCR failed: {result.Error}");
            Console.ResetColor();
        }
    }
}