// <auto-generated />
using System;
using ExxerCube.Prisma.Infrastructure.Database.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExxerCube.Prisma.Infrastructure.Database.Migrations
{
    [DbContext(typeof(PrismaDbContext))]
    partial class PrismaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ExxerCube.Prisma.Domain.Entities.AuditRecord", b =>
                {
                    b.Property<string>("AuditId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ActionDetails")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<int>("ActionType")
                        .HasColumnType("int");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("FileId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Stage")
                        .HasColumnType("int");

                    b.Property<bool>("Success")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("AuditId");

                    b.HasIndex("ActionType")
                        .HasDatabaseName("IX_AuditRecords_ActionType");

                    b.HasIndex("CorrelationId")
                        .HasDatabaseName("IX_AuditRecords_CorrelationId");

                    b.HasIndex("FileId")
                        .HasDatabaseName("IX_AuditRecords_FileId");

                    b.HasIndex("Timestamp")
                        .HasDatabaseName("IX_AuditRecords_Timestamp");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_AuditRecords_UserId");

                    b.HasIndex("FileId", "Timestamp")
                        .HasDatabaseName("IX_AuditRecords_FileId_Timestamp");

                    b.ToTable("AuditRecords", (string)null);
                });

            modelBuilder.Entity("ExxerCube.Prisma.Domain.Entities.FileMetadata", b =>
                {
                    b.Property<string>("FileId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Checksum")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("DownloadDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DownloadTimestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("EvidenceHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<int>("Format")
                        .HasColumnType("int");

                    b.Property<string>("LinkedExpediente")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LinkedOficio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SignatureType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.HasKey("FileId");

                    b.HasIndex("Checksum")
                        .HasDatabaseName("IX_FileMetadata_Checksum");

                    b.HasIndex("DownloadTimestamp")
                        .HasDatabaseName("IX_FileMetadata_DownloadTimestamp");

                    b.ToTable("FileMetadata", (string)null);
                });

            modelBuilder.Entity("ExxerCube.Prisma.Domain.Entities.Persona", b =>
                {
                    b.Property<int>("ParteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ParteId"));

                    b.Property<string>("Caracter")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Complementarios")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Domicilio")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Materno")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Paterno")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PersonaTipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Relacion")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Rfc")
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("RfcVariants")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.HasKey("ParteId");

                    b.HasIndex("Rfc")
                        .HasDatabaseName("IX_Persona_Rfc");

                    b.ToTable("Persona", (string)null);
                });

            modelBuilder.Entity("ExxerCube.Prisma.Domain.Entities.RequirementTypeDictionary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("DiscoveredAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("DiscoveredFromDocument")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("KeywordPattern")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.HasKey("Id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_RequirementTypeDictionary_IsActive");

                    b.ToTable("RequirementTypeDictionary", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 100,
                            CreatedBy = "System",
                            DiscoveredAt = new DateTime(2025, 1, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Solicitud de Información",
                            IsActive = true,
                            KeywordPattern = "solicita información|estados de cuenta",
                            Name = "InformationRequest",
                            Notes = "Art. 142 LIC - Judicial/Fiscal/Administrative information requests"
                        },
                        new
                        {
                            Id = 101,
                            CreatedBy = "System",
                            DiscoveredAt = new DateTime(2025, 1, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Aseguramiento/Bloqueo",
                            IsActive = true,
                            KeywordPattern = "asegurar|bloquear|embargar",
                            Name = "Aseguramiento",
                            Notes = "Art. 2(V)(b) - SAME DAY execution required"
                        },
                        new
                        {
                            Id = 102,
                            CreatedBy = "System",
                            DiscoveredAt = new DateTime(2025, 1, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Desbloqueo",
                            IsActive = true,
                            KeywordPattern = "desbloquear|liberar",
                            Name = "Desbloqueo",
                            Notes = "R29 Type 102 - Release of frozen funds"
                        },
                        new
                        {
                            Id = 103,
                            CreatedBy = "System",
                            DiscoveredAt = new DateTime(2025, 1, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Transferencia Electrónica",
                            IsActive = true,
                            KeywordPattern = "transferir.*CLABE|CLABE.*transferir",
                            Name = "Transferencia",
                            Notes = "R29 Type 103 - Electronic transfer to government account"
                        },
                        new
                        {
                            Id = 104,
                            CreatedBy = "System",
                            DiscoveredAt = new DateTime(2025, 1, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Situación de Fondos",
                            IsActive = true,
                            KeywordPattern = "cheque de caja|poner a disposición",
                            Name = "SituacionFondos",
                            Notes = "R29 Type 104 - Cashier's check to judicial authority"
                        },
                        new
                        {
                            Id = 999,
                            CreatedBy = "System",
                            DiscoveredAt = new DateTime(2025, 1, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Desconocido",
                            IsActive = true,
                            Name = "Unknown",
                            Notes = "Fallback for unrecognized requirement types - triggers manual review"
                        });
                });

            modelBuilder.Entity("ExxerCube.Prisma.Domain.Entities.ReviewCase", b =>
                {
                    b.Property<string>("CaseId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("AssignedTo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("ClassificationAmbiguity")
                        .HasColumnType("bit");

                    b.Property<int>("ConfidenceLevel")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FileId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("RequiresReviewReason")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("CaseId");

                    b.HasIndex("AssignedTo")
                        .HasDatabaseName("IX_ReviewCases_AssignedTo");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_ReviewCases_CreatedAt");

                    b.HasIndex("FileId")
                        .HasDatabaseName("IX_ReviewCases_FileId");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_ReviewCases_Status");

                    b.ToTable("ReviewCases", (string)null);
                });

            modelBuilder.Entity("ExxerCube.Prisma.Domain.Entities.ReviewDecision", b =>
                {
                    b.Property<string>("DecisionId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CaseId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("DecisionType")
                        .HasColumnType("int");

                    b.Property<string>("FileId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("OverriddenClassification")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("OverriddenFields")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<int>("ReviewReason")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReviewedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReviewerId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("DecisionId");

                    b.HasIndex("CaseId")
                        .HasDatabaseName("IX_ReviewDecisions_CaseId");

                    b.HasIndex("ReviewedAt")
                        .HasDatabaseName("IX_ReviewDecisions_ReviewedAt");

                    b.HasIndex("ReviewerId")
                        .HasDatabaseName("IX_ReviewDecisions_ReviewerId");

                    b.ToTable("ReviewDecisions", (string)null);
                });

            modelBuilder.Entity("ExxerCube.Prisma.Domain.Entities.SLAStatus", b =>
                {
                    b.Property<string>("FileId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("DaysPlazo")
                        .HasColumnType("int");

                    b.Property<DateTime>("Deadline")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EscalatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("EscalationLevel")
                        .HasColumnType("int");

                    b.Property<DateTime>("IntakeDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsAtRisk")
                        .HasColumnType("bit");

                    b.Property<bool>("IsBreached")
                        .HasColumnType("bit");

                    b.Property<long>("RemainingTime")
                        .HasColumnType("bigint");

                    b.HasKey("FileId");

                    b.HasIndex("Deadline")
                        .HasDatabaseName("IX_SLAStatus_Deadline");

                    b.HasIndex("EscalationLevel")
                        .HasDatabaseName("IX_SLAStatus_EscalationLevel");

                    b.HasIndex("IsAtRisk")
                        .HasDatabaseName("IX_SLAStatus_IsAtRisk");

                    b.HasIndex("IsBreached")
                        .HasDatabaseName("IX_SLAStatus_IsBreached");

                    b.ToTable("SLAStatus", (string)null);
                });

            modelBuilder.Entity("ExxerCube.Prisma.Domain.Entities.AuditRecord", b =>
                {
                    b.HasOne("ExxerCube.Prisma.Domain.Entities.FileMetadata", null)
                        .WithMany()
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("ExxerCube.Prisma.Domain.Entities.ReviewCase", b =>
                {
                    b.HasOne("ExxerCube.Prisma.Domain.Entities.FileMetadata", null)
                        .WithMany()
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ExxerCube.Prisma.Domain.Entities.ReviewDecision", b =>
                {
                    b.HasOne("ExxerCube.Prisma.Domain.Entities.ReviewCase", null)
                        .WithMany()
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ExxerCube.Prisma.Domain.Entities.SLAStatus", b =>
                {
                    b.HasOne("ExxerCube.Prisma.Domain.Entities.FileMetadata", null)
                        .WithOne()
                        .HasForeignKey("ExxerCube.Prisma.Domain.Entities.SLAStatus", "FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
