namespace ExxerCube.Prisma.Domain.ValueObjects;

/// <summary>
/// CNBV law-mandated fields for R29 compliance.
/// Contains fields required by regulatory mandate that may not appear in current XML samples.
/// These fields describe the CASE itself (domain concern), not processing metadata.
/// </summary>
/// <remarks>
/// Source: Laws/MandatoryFields_CNBV.md, DATA_MODEL.md Sections 2.1-2.4
///
/// DOMAIN SCOPE (what this class contains):
/// - Core identification fields (InternalCaseId, SourceAuthorityCode, ProcessingStatus)
/// - Classification fields (RequirementType, RequirementTypeCode)
/// - Subject information (IsPrimaryTitular)
/// - Financial information (BranchCode, AccountNumber, amounts, etc.)
///
/// NOT INCLUDED (infrastructure concerns):
/// - Semantic analysis (5 situations) → Output of classification algorithms
/// - Processing metadata (audit trail, confidence scores) → Infrastructure tracking
///
/// All fields nullable until:
/// - CNBV updates XML schema to include them, OR
/// - Bank systems provide data via lookup, OR
/// - Manual enrichment occurs
/// </remarks>
public class LawMandatedFields
{
    // ============================================================================
    // Section 2.1: Core Identification & Tracking
    // ============================================================================

    /// <summary>
    /// Internal system-generated case ID (GUID).
    /// Generated by Prisma on intake.
    /// </summary>
    public Guid? InternalCaseId { get; set; }

    /// <summary>
    /// Authority code from catalog (e.g., "SAT-AGAF").
    /// Populated via Authority Catalog lookup.
    /// </summary>
    public string? SourceAuthorityCode { get; set; }

    /// <summary>
    /// Processing workflow status.
    /// Values: "Received", "InReview", "Completed_Auto", "Completed_Manual", "Rejected"
    /// </summary>
    public string? ProcessingStatus { get; set; }

    // ============================================================================
    // Section 2.2: SLA & Classification
    // ============================================================================

    /// <summary>
    /// Requirement type classification (e.g., "Aseguramiento", "Hacendario").
    /// Output of classification rules (ClassificationRules.md).
    /// </summary>
    public string? RequirementType { get; set; }

    /// <summary>
    /// Requirement type numeric code (100-104, etc.).
    /// Corresponds to R29 report column 35.
    /// </summary>
    public int? RequirementTypeCode { get; set; }

    // ============================================================================
    // Section 2.3: Subject & Account Holder Information
    // ============================================================================

    /// <summary>
    /// Indicates if this subject is the primary account holder.
    /// Computed: first subject in SolicitudPartes is primary.
    /// </summary>
    public bool? IsPrimaryTitular { get; set; }

    // ============================================================================
    // Section 2.4: Financial Information (R29 Report Data)
    // ============================================================================
    // NOTE: These fields come from BANK SYSTEMS, not from CNBV XML.
    // Populated AFTER account lookup in bank's internal systems.

    /// <summary>
    /// Bank branch code where account is held.
    /// R29 report column 25.
    /// Source: Bank's internal systems (post-lookup).
    /// </summary>
    public string? BranchCode { get; set; }

    /// <summary>
    /// INEGI state code for geographic reporting.
    /// R29 report column 26.
    /// Source: Bank's internal geographic catalog.
    /// </summary>
    public int? StateINEGI { get; set; }

    /// <summary>
    /// Account number (from bank system lookup).
    /// R29 report column 31.
    /// NOTE: May also exist in SolicitudEspecifica.Cuentas if provided in XML.
    /// </summary>
    public string? AccountNumber { get; set; }

    /// <summary>
    /// Product type code (101 = Depósito a la Vista, 13 = Inversión, etc.).
    /// R29 report column 32.
    /// Source: Bank's product catalog.
    /// </summary>
    public int? ProductType { get; set; }

    /// <summary>
    /// Account currency (0 = MXN, 1 = USD, 2 = Other).
    /// R29 report columns 33, 41.
    /// Source: Bank account data.
    /// </summary>
    public string? Currency { get; set; }

    /// <summary>
    /// Initial amount blocked/frozen at execution.
    /// R29 report column 34.
    /// Converted to MXN if necessary.
    /// </summary>
    public decimal? InitialBlockedAmount { get; set; }

    /// <summary>
    /// Amount of specific operation (unblock, transfer, etc.).
    /// R29 report column 40.
    /// </summary>
    public decimal? OperationAmount { get; set; }

    /// <summary>
    /// Final account balance after operation.
    /// R29 report column 42.
    /// </summary>
    public decimal? FinalBalance { get; set; }

    /// <summary>
    /// Validation state for law-mandated fields.
    /// </summary>
    public ValidationState Validation { get; } = new();
}
