// <copyright file="SourceType.cs" company="Exxerpro Solutions SA de CV">
// Copyright (c) Exxerpro Solutions SA de CV. All rights reserved.
// </copyright>

namespace ExxerCube.Prisma.Domain.Enum;

/// <summary>
/// Represents the source of extracted Expediente data for multi-source fusion.
/// Each source has different reliability characteristics affecting fusion decisions.
/// </summary>
/// <remarks>
/// Base reliability ranking (before OCR quality adjustment):
/// 1. PDF_OCR_CNBV (0.85) - Official CNBV-generated PDF with good OCR quality
/// 2. DOCX_OCR_Authority (0.70) - Authority-generated DOCX, variable OCR quality
/// 3. XML_HandFilled (0.60) - Manually entered XML data, prone to typos and catalog mismatches
///
/// Actual reliability is dynamically calculated using OCR confidence, image quality metrics,
/// and extraction success rates. See IFusionExpediente for fusion algorithm details.
/// </remarks>
public class SourceType : EnumModel
{
    /// <summary>
    /// XML file manually filled by bank staff from physical/scanned documents.
    /// Prone to typos, incorrect catalog values, and format inconsistencies.
    /// Base reliability: 0.60 (adjusted by pattern validation and catalog matching).
    /// </summary>
    public static readonly SourceType XML_HandFilled
        = new(1, "XML_HandFilled", "XML Manual");

    /// <summary>
    /// PDF generated by CNBV system with OCR extraction.
    /// Generally high quality but subject to OCR errors on poor scans.
    /// Base reliability: 0.85 (adjusted by OCR confidence and image quality).
    /// </summary>
    public static readonly SourceType PDF_OCR_CNBV
        = new(2, "PDF_OCR_CNBV", "PDF CNBV");

    /// <summary>
    /// DOCX file from issuing authority (SAT, UIF, Juzgado, etc.) with OCR extraction.
    /// Quality varies significantly by authority and scanning equipment.
    /// Base reliability: 0.70 (adjusted by OCR confidence and image quality).
    /// </summary>
    public static readonly SourceType DOCX_OCR_Authority
        = new(3, "DOCX_OCR_Authority", "DOCX Autoridad");

    /// <summary>
    /// Initializes a new instance of the <see cref="SourceType"/> class.
    /// Parameterless constructor required by EF Core for entity materialization.
    /// </summary>
    public SourceType()
    {
    }

    /// <summary>
    /// Initializes a new instance of the <see cref="SourceType"/> class with specified values.
    /// </summary>
    /// <param name="value">The source type code.</param>
    /// <param name="name">The internal name.</param>
    /// <param name="displayName">The display name.</param>
    private SourceType(int value, string name, string displayName = "")
        : base(value, name, displayName)
    {
    }

    /// <summary>
    /// Creates a SourceType instance from an integer value.
    /// </summary>
    /// <param name="value">The source type code.</param>
    /// <returns>Matching SourceType instance.</returns>
    public static SourceType FromValue(int value) => FromValue<SourceType>(value);

    /// <summary>
    /// Creates a SourceType instance from a name.
    /// </summary>
    /// <param name="name">The internal name.</param>
    /// <returns>Matching SourceType instance.</returns>
    public static SourceType FromName(string name) => FromName<SourceType>(name);

    /// <summary>
    /// Creates a SourceType instance from a display name.
    /// </summary>
    /// <param name="displayName">The display name.</param>
    /// <returns>Matching SourceType instance.</returns>
    public static SourceType FromDisplayName(string displayName) => FromDisplayName<SourceType>(displayName);

    /// <summary>
    /// Implicit conversion to int for database storage and comparisons.
    /// </summary>
    /// <param name="type">The SourceType to convert.</param>
    public static implicit operator int(SourceType type) => type.Value;

    /// <summary>
    /// Implicit conversion from int to SourceType.
    /// </summary>
    /// <param name="value">The source type code.</param>
    public static implicit operator SourceType(int value) => FromValue(value);
}
