// Global using directives for Infrastructure.Extraction Tests

global using System;
global using System.Collections.Generic;
global using System.Diagnostics;
global using System.Diagnostics.CodeAnalysis;
global using System.IO;
global using System.Linq;
global using System.Linq.Expressions;
global using System.Reflection;
global using System.Runtime.InteropServices;
global using System.Security.Cryptography;
global using System.Security.Cryptography.X509Certificates;
global using System.Threading;
global using System.Threading.Tasks;
global using DocumentFormat.OpenXml;
global using DocumentFormat.OpenXml.Math;
global using DocumentFormat.OpenXml.Packaging;
global using DocumentFormat.OpenXml.Wordprocessing;
global using ExxerCube.Prisma.Domain;
global using ExxerCube.Prisma.Domain.Entities;
global using ExxerCube.Prisma.Infrastructure.Extraction;
global using ExxerCube.Prisma.Domain.Interfaces;
global using ExxerCube.Prisma.Domain.Models;
global using ExxerCube.Prisma.Domain.Sources;
global using ExxerCube.Prisma.Domain.ValueObjects;
global using ExxerCube.Prisma.Testing.Abstractions;
global using ExxerCube.Prisma.Testing.Infrastructure;
global using ExxerCube.Prisma.Testing.Infrastructure.TestData;
global using IndQuestResults;
global using IndQuestResults.Async;
global using IndQuestResults.Operations;
global using Meziantou.Extensions.Logging.Xunit.v3;
global using Microsoft.Extensions.Logging;
global using NSubstitute;
global using Shouldly;
global using Xunit;
global using Xunit.Sdk;

