using ExxerCube.Prisma.Infrastructure.Extraction.Ocr.GotOcr2;
using Microsoft.Extensions.Logging;

namespace ExxerCube.Prisma.ConsoleApp.GotOcr2Demo;

/// <summary>
/// Console demo application for GOT-OCR2 OCR executor integration test
/// </summary>
internal class Program
{
    private static async Task<int> Main(string[] args)
    {
        // Configure Serilog early for diagnostics
        var baseDirectory = AppDomain.CurrentDomain.BaseDirectory;
        var logFilePath = Path.Combine(baseDirectory, "logs", "gotocr2-demo-.log");

        Log.Logger = new LoggerConfiguration()
            .MinimumLevel.Debug()
            .WriteTo.Console(outputTemplate: "[{Timestamp:HH:mm:ss} {Level:u3}] {Message:lj}{NewLine}{Exception}")
            .WriteTo.File(
                logFilePath,
                rollingInterval: RollingInterval.Day,
                outputTemplate: "{Timestamp:yyyy-MM-dd HH:mm:ss.fff zzz} [{Level:u3}] {Message:lj}{NewLine}{Exception}",
                retainedFileCountLimit: 7)
            .CreateLogger();

        Log.Information("=== ExxerCube.Prisma - GOT-OCR2 Integration Demo ===");
        Log.Information("Log file: {LogFilePath}", logFilePath);

        try
        {
            // Build host with Python environment
            var builder = Host.CreateApplicationBuilder(args);

            // Setup Python environment for GOT-OCR2
            // Files are copied to output directory/python by build
            var pythonLibPath = Path.Combine(baseDirectory, "python");

            Log.Information("Python library path: {PythonLibPath}", pythonLibPath);
            Log.Information("Base directory: {BaseDirectory}", baseDirectory);

            var venvPath = Path.Combine(baseDirectory, ".venv_gotor2");

            // Configure CSnakes Python environment (proven configuration from GotOcr2Sample)
            var requirementsPath = Path.Combine(baseDirectory, "requirements.txt");
            builder.Services
                .WithPython()
                .WithHome(pythonLibPath)
                .WithVirtualEnvironment(venvPath)
                .FromRedistributable("3.13")
                .WithPipInstaller(requirementsPath);

            // Add Serilog
            builder.Services.AddSerilog(Log.Logger);

            // Register OCR executor
            builder.Services.AddScoped<IOcrExecutor, GotOcr2OcrExecutor>();

            var host = builder.Build();
            var logger = host.Services.GetRequiredService<Microsoft.Extensions.Logging.ILogger<Program>>();
            // CSnakes will automatically create venv and install packages on first run
            Log.Information("Initializing Python environment (this may take several minutes on first run)...");
            Log.Information("- Downloading Python 3.13 redistributable if needed");
            Log.Information("- Creating virtual environment");
            Log.Information("- Installing PyTorch, transformers, and GOT-OCR2 dependencies");
            Log.Information("- Downloading GOT-OCR2 model (~3-5GB) on first health check");

            // Get services
            var pythonEnv = host.Services.GetRequiredService<IPythonEnvironment>();
            var executor = host.Services.GetRequiredService<IOcrExecutor>();

            Log.Information("✓ Python environment initialized");

            // Run demos
            await RunHealthCheckDemo(pythonEnv);
            await RunOcrDemo(executor, logger, args);

            Log.Information("Demo completed successfully");
            return 0;
        }
        catch (Exception ex)
        {
            Log.Fatal(ex, "Fatal error in GOT-OCR2 demo");
            return 1;
        }
        finally
        {
            await Log.CloseAndFlushAsync();
        }
    }

    private static async Task RunHealthCheckDemo(IPythonEnvironment pythonEnv)
    {
        Console.WriteLine("\n--- Health Check ---");

        try
        {
            // Use the strongly-typed interface generated by CSnakes
            var module = pythonEnv.GotOcr2Wrapper();

            // Get version and model info
            var version = module.GetVersion();
            var modelInfo = module.GetModelInfo();

            Console.WriteLine($"✓ Module version: {version}");
            Console.WriteLine($"✓ Model info: {modelInfo}");

            // Run health check
            Console.WriteLine("\nRunning health check (this will download GOT-OCR2 model on first run ~3-5GB)...");
            var isHealthy = module.HealthCheck();

            if (isHealthy)
            {
                Console.ForegroundColor = ConsoleColor.Green;
                Console.WriteLine("✓ Health check PASSED - GOT-OCR2 model loaded successfully");
                Console.ResetColor();
            }
            else
            {
                Console.ForegroundColor = ConsoleColor.Yellow;
                Console.WriteLine("⚠ Health check FAILED");
                Console.ResetColor();
            }
        }
        catch (Exception ex)
        {
            Console.ForegroundColor = ConsoleColor.Red;
            Console.WriteLine($"✗ Health check error: {ex.Message}");
            if (ex.InnerException != null)
            {
                Console.WriteLine($"✗ Inner error: {ex.InnerException.Message}");
            }
            Console.ResetColor();
        }
    }

    private static async Task RunOcrDemo(IOcrExecutor executor, Microsoft.Extensions.Logging.ILogger logger, string[] args)
    {
        Console.WriteLine("\n--- OCR Execution Demo ---");

        // Use file locator helper with detailed logging
        var imagePath = FixtureFileLocator.LocateFixtureImage(logger, args);

        if (imagePath == null)
        {
            Console.WriteLine("\n⚠ Could not locate any fixture images.");
            Console.WriteLine("Usage: dotnet run <image-path>");
            Console.WriteLine("       dotnet run \"C:\\path\\to\\document.jpg\"");
            return;
        }

        Log.Information("✓ File located: {FileName}", Path.GetFileName(imagePath));

        // Check file type
        var fileExtension = Path.GetExtension(imagePath).ToLowerInvariant();
        var isPdf = fileExtension == ".pdf";

        if (isPdf)
        {
            Log.Information("PDF file detected - GOT-OCR2 supports PDF natively!");

            // Get page count for logging
            try
            {
                var pdfBytes = await File.ReadAllBytesAsync(imagePath);
                using var pdfDocument = PdfDocument.Open(pdfBytes);
                Log.Information("PDF contains {PageCount} page(s)", pdfDocument.NumberOfPages);
            }
            catch (Exception ex)
            {
                Log.Warning(ex, "Could not read PDF metadata, will attempt OCR anyway");
            }
        }

        // Read file (PDF or image) - GOT-OCR2 handles both
        Log.Debug("Reading file: {FilePath}", imagePath);
        var fileBytes = await File.ReadAllBytesAsync(imagePath);
        Log.Debug("File size: {Size:N0} bytes", fileBytes.Length);

        var imageData = new ImageData(fileBytes, imagePath);

        // Configure OCR (Spanish with moderate confidence threshold)
        var config = new OCRConfig(
            language: "spa",
            oem: 1,
            psm: 6,
            fallbackLanguage: "eng",
            confidenceThreshold: 0.7f
        );

        Log.Information("Running OCR with language={Language}, threshold={Threshold:F2}", config.Language, config.ConfidenceThreshold);

        // Execute OCR
        var startTime = DateTime.UtcNow;
        Log.Debug("Starting OCR execution at {StartTime}", startTime);
        var result = await executor.ExecuteOcrAsync(imageData, config);
        var elapsed = DateTime.UtcNow - startTime;
        Log.Debug("OCR execution completed in {Elapsed:F2}s", elapsed.TotalSeconds);

        // Display results
        if (result.IsSuccess)
        {
            var ocrResult = result.Value;

            Log.Information("✓ OCR succeeded");
            Log.Information("Results:");
            Log.Information("  Text length: {Length} characters", ocrResult?.Text.Length ?? 0);
            Log.Information("  Confidence avg: {ConfidenceAvg:F2}%", ocrResult?.ConfidenceAvg);
            Log.Information("  Confidence median: {ConfidenceMedian:F2}%", ocrResult?.ConfidenceMedian);
            Log.Information("  Language: {Language}", ocrResult?.LanguageUsed);
            Log.Information("  Processing time: {ProcessingTime:F2}s", elapsed.TotalSeconds);

            var preview = ocrResult?.Text.Length > 500
                ? ocrResult.Text.Substring(0, 500) + "..."
                : ocrResult?.Text;

            Log.Information("Extracted text (first 500 chars):");
            Log.Information("{Separator}", new string('-', 80));
            Log.Information("{Preview}", preview);
            Log.Information("{Separator}", new string('-', 80));
        }
        else
        {
            Log.Error("✗ OCR failed: {Error}", result.Error);
        }
    }
}